version: '3'

services:
  cassandra:
      container_name: cassandra
      build:
        context: ./cassandra
        dockerfile: Dockerfile
      ports:
        - "9042:9042"
      environment:
        - "MAX_HEAP_SIZE=256M"
        - "HEAP_NEWSIZE=128M"
      restart: always
      networks:
        -  netabet
  
  backend:
      container_name: backend
      build:
        context: ./backend
        dockerfile: Dockerfile
      depends_on:
        -  cassandra
      environment:
        CASS_HOST: cassandra
      ports:
        -  9003:9003
      networks:
        -  netabet
  
  frontend:
      container_name: frontend
      build:
        context: ./frontend
        dockerfile: Dockerfile
      depends_on:
        -  backend
      environment:
        API_URL: http://backend:9003/api/text_field_1/ahmad
      ports:
        -  3000:3000
      networks:
        -  netabet
  
networks:
  netabet:
    driver: bridge
