version: '3'

services:
  cassandra:
      image: cassandra:3.11.2
      container_name: cassandra
      ports:
        - "9042:9042"
      environment:
        - "MAX_HEAP_SIZE=256M"
        - "HEAP_NEWSIZE=128M"
      restart: always
      healthcheck:
        test: ["CMD", "cqlsh", "-u cassandra", "-p cassandra" ,"-e describe keyspaces"]
        interval: 15s
        timeout: 10s
        retries: 10

  # cassandra-load-keyspace:
  #     container_name: cassandra-load-keyspace
  #     build: ./
  #     depends_on:
  #       -  cassandra
  #     volumes:
  #       - ./initial-seed.cql:/schema.cql
  #     command: /bin/bash -c "echo loading cassandra keyspace && cqlsh cassandra -f /schema.cql"
  
  
  backend:
      container_name: backend
      build:
        context: ./backend
        dockerfile: Dockerfile
      depends_on:
        -  cassandra
      environment:
        CASS_HOST: cassandra
      ports:
        -  9003:9003
  
  frontend:
      container_name: frontend
      build:
        context: ./frontend
        dockerfile: Dockerfile
      depends_on:
        -  backend
      environment:
        API_URL: http://backend:9003/api/text_field_1/ahmad
      ports:
        -  3000:3000